# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from grpc_src.models import common_pb2 as grpc__src_dot_models_dot_common__pb2
from grpc_src.models import setting_pb2 as grpc__src_dot_models_dot_setting__pb2


class SettingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDataBaseTable = channel.unary_unary(
            '/setting.services.Setting/GetDataBaseTable',
            request_serializer=grpc__src_dot_models_dot_setting__pb2.GetDataBaseTableRequest.SerializeToString,
            response_deserializer=grpc__src_dot_models_dot_setting__pb2.GetDataBaseTableResponse.FromString,
        )
        self.GetLastRecords = channel.unary_unary(
            '/setting.services.Setting/GetLastRecords',
            request_serializer=grpc__src_dot_models_dot_setting__pb2.GetLastRecordsRequest.SerializeToString,
            response_deserializer=grpc__src_dot_models_dot_setting__pb2.GetLastRecordsResponse.FromString,
        )
        self.CheckDataBaseConnection = channel.unary_unary(
            '/setting.services.Setting/CheckDataBaseConnection',
            request_serializer=grpc__src_dot_models_dot_setting__pb2.RequestCheckDataBaseConnection.SerializeToString,
            response_deserializer=grpc__src_dot_models_dot_setting__pb2.ResponseCheckDataBaseConnection.FromString,
        )
        self.CheckDiskCapacity = channel.unary_unary(
            '/setting.services.Setting/CheckDiskCapacity',
            request_serializer=grpc__src_dot_models_dot_setting__pb2.RequestCheckDiskCapacity.SerializeToString,
            response_deserializer=grpc__src_dot_models_dot_setting__pb2.ResponseCheckDiskCapacity.FromString,
        )
        self.PreviewCsvData = channel.unary_unary(
            '/setting.services.Setting/PreviewCsvData',
            request_serializer=grpc__src_dot_models_dot_common__pb2.GenericRequestParams.SerializeToString,
            response_deserializer=grpc__src_dot_models_dot_common__pb2.GenericResponse.FromString,
        )
        self.GenericGrpcMethod = channel.unary_unary(
            '/setting.services.Setting/GenericGrpcMethod',
            request_serializer=grpc__src_dot_models_dot_common__pb2.GenericRequestParams.SerializeToString,
            response_deserializer=grpc__src_dot_models_dot_common__pb2.GenericResponse.FromString,
        )
        self.GenericGrpcMethodStream = channel.unary_stream(
            '/setting.services.Setting/GenericGrpcMethodStream',
            request_serializer=grpc__src_dot_models_dot_common__pb2.GenericRequestParams.SerializeToString,
            response_deserializer=grpc__src_dot_models_dot_common__pb2.GenericResponse.FromString,
        )


class SettingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetDataBaseTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLastRecords(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckDataBaseConnection(self, request, context):
        """Check database connection with request's configuration."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckDiskCapacity(self, request, context):
        """Check disk capacity of Bridge Station & Postgres DB."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PreviewCsvData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenericGrpcMethod(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenericGrpcMethodStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SettingServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'GetDataBaseTable': grpc.unary_unary_rpc_method_handler(
            servicer.GetDataBaseTable,
            request_deserializer=grpc__src_dot_models_dot_setting__pb2.GetDataBaseTableRequest.FromString,
            response_serializer=grpc__src_dot_models_dot_setting__pb2.GetDataBaseTableResponse.SerializeToString,
        ),
        'GetLastRecords': grpc.unary_unary_rpc_method_handler(
            servicer.GetLastRecords,
            request_deserializer=grpc__src_dot_models_dot_setting__pb2.GetLastRecordsRequest.FromString,
            response_serializer=grpc__src_dot_models_dot_setting__pb2.GetLastRecordsResponse.SerializeToString,
        ),
        'CheckDataBaseConnection': grpc.unary_unary_rpc_method_handler(
            servicer.CheckDataBaseConnection,
            request_deserializer=grpc__src_dot_models_dot_setting__pb2.RequestCheckDataBaseConnection.FromString,
            response_serializer=grpc__src_dot_models_dot_setting__pb2.ResponseCheckDataBaseConnection.SerializeToString,
        ),
        'CheckDiskCapacity': grpc.unary_unary_rpc_method_handler(
            servicer.CheckDiskCapacity,
            request_deserializer=grpc__src_dot_models_dot_setting__pb2.RequestCheckDiskCapacity.FromString,
            response_serializer=grpc__src_dot_models_dot_setting__pb2.ResponseCheckDiskCapacity.SerializeToString,
        ),
        'PreviewCsvData': grpc.unary_unary_rpc_method_handler(
            servicer.PreviewCsvData,
            request_deserializer=grpc__src_dot_models_dot_common__pb2.GenericRequestParams.FromString,
            response_serializer=grpc__src_dot_models_dot_common__pb2.GenericResponse.SerializeToString,
        ),
        'GenericGrpcMethod': grpc.unary_unary_rpc_method_handler(
            servicer.GenericGrpcMethod,
            request_deserializer=grpc__src_dot_models_dot_common__pb2.GenericRequestParams.FromString,
            response_serializer=grpc__src_dot_models_dot_common__pb2.GenericResponse.SerializeToString,
        ),
        'GenericGrpcMethodStream': grpc.unary_stream_rpc_method_handler(
            servicer.GenericGrpcMethodStream,
            request_deserializer=grpc__src_dot_models_dot_common__pb2.GenericRequestParams.FromString,
            response_serializer=grpc__src_dot_models_dot_common__pb2.GenericResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler('setting.services.Setting', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class Setting(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetDataBaseTable(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/setting.services.Setting/GetDataBaseTable',
            grpc__src_dot_models_dot_setting__pb2.GetDataBaseTableRequest.SerializeToString,
            grpc__src_dot_models_dot_setting__pb2.GetDataBaseTableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetLastRecords(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/setting.services.Setting/GetLastRecords',
            grpc__src_dot_models_dot_setting__pb2.GetLastRecordsRequest.SerializeToString,
            grpc__src_dot_models_dot_setting__pb2.GetLastRecordsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def CheckDataBaseConnection(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/setting.services.Setting/CheckDataBaseConnection',
            grpc__src_dot_models_dot_setting__pb2.RequestCheckDataBaseConnection.SerializeToString,
            grpc__src_dot_models_dot_setting__pb2.ResponseCheckDataBaseConnection.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def CheckDiskCapacity(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/setting.services.Setting/CheckDiskCapacity',
            grpc__src_dot_models_dot_setting__pb2.RequestCheckDiskCapacity.SerializeToString,
            grpc__src_dot_models_dot_setting__pb2.ResponseCheckDiskCapacity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def PreviewCsvData(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/setting.services.Setting/PreviewCsvData',
            grpc__src_dot_models_dot_common__pb2.GenericRequestParams.SerializeToString,
            grpc__src_dot_models_dot_common__pb2.GenericResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GenericGrpcMethod(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/setting.services.Setting/GenericGrpcMethod',
            grpc__src_dot_models_dot_common__pb2.GenericRequestParams.SerializeToString,
            grpc__src_dot_models_dot_common__pb2.GenericResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GenericGrpcMethodStream(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/setting.services.Setting/GenericGrpcMethodStream',
            grpc__src_dot_models_dot_common__pb2.GenericRequestParams.SerializeToString,
            grpc__src_dot_models_dot_common__pb2.GenericResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
