# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_src/setting/services.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1fgrpc_src/setting/services.proto\x12\x10setting.services\x1a\x1dgrpc_src/models/setting.proto\x1a\x1cgrpc_src/models/common.proto2\xd8\x05\n\x07Setting\x12g\n\x10GetDataBaseTable\x12\'.models.setting.GetDataBaseTableRequest\x1a(.models.setting.GetDataBaseTableResponse"\x00\x12\x61\n\x0eGetLastRecords\x12%.models.setting.GetLastRecordsRequest\x1a&.models.setting.GetLastRecordsResponse"\x00\x12|\n\x17\x43heckDataBaseConnection\x12..models.setting.RequestCheckDataBaseConnection\x1a/.models.setting.ResponseCheckDataBaseConnection"\x00\x12j\n\x11\x43heckDiskCapacity\x12(.models.setting.RequestCheckDiskCapacity\x1a).models.setting.ResponseCheckDiskCapacity"\x00\x12W\n\x0ePreviewCsvData\x12#.models.common.GenericRequestParams\x1a\x1e.models.common.GenericResponse"\x00\x12Z\n\x11GenericGrpcMethod\x12#.models.common.GenericRequestParams\x1a\x1e.models.common.GenericResponse"\x00\x12\x62\n\x17GenericGrpcMethodStream\x12#.models.common.GenericRequestParams\x1a\x1e.models.common.GenericResponse"\x00\x30\x01\x62\x06proto3'
)


_SETTING = DESCRIPTOR.services_by_name['Setting']
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _SETTING._serialized_start = 115
    _SETTING._serialized_end = 843
# @@protoc_insertion_point(module_scope)
