"""bridge_sprint_189_add_format_column_into_cfg_process

Revision ID: 04b7b9ab99f5
Revises: 4b84180358d9
Create Date: 2023-07-07 14:31:53.760234

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '04b7b9ab99f5'
down_revision = '4b84180358d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'cfg_process_unused_column',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('process_id', sa.Integer(), nullable=True),
        sa.Column('column_name', sa.Text(), nullable=True),
        sa.Column('created_at', sa.Text(), nullable=True),
        sa.Column('updated_at', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['process_id'], ['cfg_process.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sqlite_autoincrement=True,
    )
    op.add_column('cfg_process_column', sa.Column('format', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cfg_process_column', 'format')
    op.drop_table('cfg_process_unused_column')
    # ### end Alembic commands ###
