"""Add reletionship cfg_process_column with cfg_process_function_column

Revision ID: 1a675cde28b6
Revises: 66a9c979db74
Create Date: 2024-04-16 11:32:14.169496

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '1a675cde28b6'
down_revision = '66a9c979db74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'cfg_process_function_column', 'cfg_process_column', ['id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cfg_process_function_column', type_='foreignkey')
    # ### end Alembic commands ###
