"""Add prod family in mapping process data

Revision ID: 2d388310197b
Revises: 362f5ccfac08
Create Date: 2023-09-06 15:23:51.316921

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2d388310197b'
down_revision = '362f5ccfac08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mapping_process_data', sa.Column('t_prod_family_abbr', sa.Text(), nullable=True))
    op.add_column('mapping_process_data', sa.Column('t_prod_family_id', sa.Text(), nullable=True))
    op.add_column('mapping_process_data', sa.Column('t_prod_family_name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mapping_process_data', 't_prod_family_name')
    op.drop_column('mapping_process_data', 't_prod_family_id')
    op.drop_column('mapping_process_data', 't_prod_family_abbr')
    # ### end Alembic commands ###
