"""Add n rows and transpose column

Revision ID: 341a680e29bb
Revises: 60b85352e724
Create Date: 2024-06-14 11:22:37.533876

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '341a680e29bb'
down_revision = '60b85352e724'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cfg_data_source_csv', sa.Column('is_transpose', sa.Boolean(), nullable=True))
    op.add_column('cfg_data_source_csv', sa.Column('n_rows', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cfg_data_source_csv', 'n_rows')
    op.drop_column('cfg_data_source_csv', 'is_transpose')
    # ### end Alembic commands ###
