"""Set order non null

Revision ID: 35633b04b8af
Revises: f1d473330287
Create Date: 2024-05-23 09:42:24.791491

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '35633b04b8af'
down_revision = 'f1d473330287'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    update_sql = '''
UPDATE cfg_process_function_column a
   SET "order" = b."order"
  FROM (SELECT f.id, ROW_NUMBER() OVER (PARTITION BY p.process_id) AS "order"
          FROM cfg_process_function_column f
                   LEFT JOIN cfg_process_column p
                   ON f.process_column_id = p.id) b
 WHERE a.id = b.id;
'''
    conn.execute(sa.text(update_sql))
    op.alter_column('cfg_process_function_column', 'order', existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cfg_process_function_column', 'order', existing_type=sa.INTEGER(), nullable=True)

    update_sql = '''
update cfg_process_function_column
set "order" = null
where 1 = 1;
'''
    conn = op.get_bind()
    conn.execute(sa.text(update_sql))
    # ### end Alembic commands ###
