"""Add new columns to mapping tables

Revision ID: 362f5ccfac08
Revises: 45b435f9895f
Create Date: 2023-07-28 15:12:23.116263

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '362f5ccfac08'
down_revision = '45b435f9895f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cfg_filter', 'repo_id')
    op.drop_column('cfg_filter_detail', 'repo_id')
    op.drop_column('cfg_trace_key', 'repo_id')
    op.drop_column('cfg_user_setting', 'repo_id')
    op.drop_column('cfg_visualization', 'repo_id')

    op.add_column('m_part_type', sa.Column('part_abbr_en', sa.Text(), nullable=True))
    op.add_column('m_part_type', sa.Column('part_abbr_jp', sa.Text(), nullable=True))
    op.add_column('m_part_type', sa.Column('part_abbr_local', sa.Text(), nullable=True))

    op.add_column('m_prod', sa.Column('prod_factid', sa.Text(), nullable=True))

    op.alter_column('m_prod_family', 'prod_factid', new_column_name='prod_family_factid')

    op.add_column('mapping_factory_machine', sa.Column('t_dept_abbr', sa.Text(), nullable=True))
    op.add_column('mapping_factory_machine', sa.Column('t_equip_no', sa.Text(), nullable=True))
    op.add_column('mapping_factory_machine', sa.Column('t_equip_product_date', sa.Text(), nullable=True))
    op.add_column('mapping_factory_machine', sa.Column('t_equip_product_no', sa.Text(), nullable=True))
    op.add_column('mapping_factory_machine', sa.Column('t_factory_abbr', sa.Text(), nullable=True))
    op.add_column('mapping_factory_machine', sa.Column('t_line_no', sa.Text(), nullable=True))
    op.add_column('mapping_factory_machine', sa.Column('t_location_abbr', sa.Text(), nullable=True))
    op.add_column('mapping_factory_machine', sa.Column('t_location_name', sa.Text(), nullable=True))
    op.add_column('mapping_factory_machine', sa.Column('t_outsource', sa.Text(), nullable=True))
    op.add_column('mapping_factory_machine', sa.Column('t_plant_abbr', sa.Text(), nullable=True))
    op.add_column('mapping_factory_machine', sa.Column('t_process_abbr', sa.Text(), nullable=True))
    op.add_column('mapping_factory_machine', sa.Column('t_prod_abbr', sa.Text(), nullable=True))
    op.add_column('mapping_factory_machine', sa.Column('t_prod_family_abbr', sa.Text(), nullable=True))
    op.add_column('mapping_factory_machine', sa.Column('t_prod_family_id', sa.Text(), nullable=True))
    op.add_column('mapping_factory_machine', sa.Column('t_prod_family_name', sa.Text(), nullable=True))
    op.add_column('mapping_factory_machine', sa.Column('t_prod_id', sa.Text(), nullable=True))
    op.add_column('mapping_factory_machine', sa.Column('t_prod_name', sa.Text(), nullable=True))
    op.add_column('mapping_factory_machine', sa.Column('t_sect_abbr', sa.Text(), nullable=True))
    op.add_column('mapping_factory_machine', sa.Column('t_sect_id', sa.Text(), nullable=True))
    op.add_column('mapping_factory_machine', sa.Column('t_sect_name', sa.Text(), nullable=True))
    op.add_column('mapping_factory_machine', sa.Column('t_station_no', sa.Text(), nullable=True))
    op.add_column('mapping_part', sa.Column('t_part_abbr', sa.Text(), nullable=True))
    op.add_column('mapping_part', sa.Column('t_part_name', sa.Text(), nullable=True))
    op.add_column('mapping_part', sa.Column('t_part_no_full', sa.Text(), nullable=True))
    op.add_column('mapping_part', sa.Column('t_part_type', sa.Text(), nullable=True))
    op.add_column('mapping_process_data', sa.Column('t_data_abbr', sa.Text(), nullable=True))
    op.add_column('mapping_process_data', sa.Column('t_process_abbr', sa.Text(), nullable=True))
    op.add_column('mapping_process_data', sa.Column('t_unit', sa.Text(), nullable=True))

    op.alter_column('mapping_process_data', 't_quality_id', new_column_name='t_data_id')
    op.alter_column('mapping_process_data', 't_quality_name', new_column_name='t_data_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('mapping_process_data', 't_data_id', new_column_name='t_quality_id')
    op.alter_column('mapping_process_data', 't_data_name', new_column_name='t_quality_name')

    op.drop_column('mapping_process_data', 't_unit')
    op.drop_column('mapping_process_data', 't_process_abbr')
    op.drop_column('mapping_process_data', 't_data_abbr')
    op.drop_column('mapping_part', 't_part_type')
    op.drop_column('mapping_part', 't_part_no_full')
    op.drop_column('mapping_part', 't_part_name')
    op.drop_column('mapping_part', 't_part_abbr')
    op.drop_column('mapping_factory_machine', 't_station_no')
    op.drop_column('mapping_factory_machine', 't_sect_name')
    op.drop_column('mapping_factory_machine', 't_sect_id')
    op.drop_column('mapping_factory_machine', 't_sect_abbr')
    op.drop_column('mapping_factory_machine', 't_prod_name')
    op.drop_column('mapping_factory_machine', 't_prod_id')
    op.drop_column('mapping_factory_machine', 't_prod_family_name')
    op.drop_column('mapping_factory_machine', 't_prod_family_id')
    op.drop_column('mapping_factory_machine', 't_prod_family_abbr')
    op.drop_column('mapping_factory_machine', 't_prod_abbr')
    op.drop_column('mapping_factory_machine', 't_process_abbr')
    op.drop_column('mapping_factory_machine', 't_plant_abbr')
    op.drop_column('mapping_factory_machine', 't_outsource')
    op.drop_column('mapping_factory_machine', 't_location_name')
    op.drop_column('mapping_factory_machine', 't_location_abbr')
    op.drop_column('mapping_factory_machine', 't_line_no')
    op.drop_column('mapping_factory_machine', 't_factory_abbr')
    op.drop_column('mapping_factory_machine', 't_equip_product_no')
    op.drop_column('mapping_factory_machine', 't_equip_product_date')
    op.drop_column('mapping_factory_machine', 't_equip_no')
    op.drop_column('mapping_factory_machine', 't_dept_abbr')

    op.alter_column('m_prod_family', 'prod_family_factid', new_column_name='prod_factid')

    op.drop_column('m_prod', 'prod_factid')

    op.drop_column('m_part_type', 'part_abbr_local')
    op.drop_column('m_part_type', 'part_abbr_jp')
    op.drop_column('m_part_type', 'part_abbr_en')
    op.add_column('cfg_visualization', sa.Column('repo_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('cfg_user_setting', sa.Column('repo_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('cfg_trace_key', sa.Column('repo_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('cfg_filter_detail', sa.Column('repo_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('cfg_filter', sa.Column('repo_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
