"""Remove column is_linking_column

Revision ID: 3e055e1a5054
Revises: 6f05b3a11d4f
Create Date: 2024-05-31 15:47:31.950502

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '3e055e1a5054'
down_revision = '6f05b3a11d4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cfg_process_column', 'is_linking_column')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'cfg_process_column',
        sa.Column('is_linking_column', sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
