"""Add column order into cfg_function_column table

Revision ID: 4e1fb8106754
Revises: a446042efa10
Create Date: 2024-05-16 10:58:03.812553

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4e1fb8106754'
down_revision = 'a446042efa10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cfg_process_column', 'column_raw_name', existing_type=sa.TEXT(), nullable=False)
    op.add_column('cfg_process_function_column', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cfg_process_function_column', 'order')
    op.alter_column('cfg_process_column', 'column_raw_name', existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###
