"""Add dummy header and column_raw_name

Revision ID: 4f6c0c6b459c
Revises: 5829a545afca
Create Date: 2024-04-03 15:52:03.891379

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4f6c0c6b459c'
down_revision = '5829a545afca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cfg_data_source_csv', sa.Column('dummy_header', sa.Boolean(), nullable=True))
    op.add_column('cfg_process_column', sa.Column('column_raw_name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cfg_process_column', 'column_raw_name')
    op.drop_column('cfg_data_source_csv', 'dummy_header')
    # ### end Alembic commands ###
