"""bridge_sprint_181

Revision ID: 52e7f724317d
Revises: 69b1c076494f
Create Date: 2023-07-07 14:27:15.888026

"""

# revision identifiers, used by Alembic.
revision = '52e7f724317d'
down_revision = '69b1c076494f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
