"""Replace source_column_name to column_raw_name

Revision ID: 609db7dc5915
Revises: 4f6c0c6b459c
Create Date: 2024-04-09 16:45:45.650747

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '609db7dc5915'
down_revision = '4f6c0c6b459c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cfg_process_column', 'master_type')
    op.drop_column('cfg_process_column', 'column_raw_name')
    op.alter_column('cfg_process_column', 'source_column_name', nullable=False, new_column_name='column_raw_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cfg_process_column', sa.Column('master_type', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('cfg_process_column', 'column_raw_name', nullable=False, new_column_name='source_column_name')
    op.add_column('cfg_process_column', sa.Column('column_raw_name', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
