"""Add delta_time and cut_off columns

Revision ID: 60b85352e724
Revises: 8600fce518a6
Create Date: 2024-06-10 10:45:40.752055

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '60b85352e724'
down_revision = '8600fce518a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cfg_trace_key', sa.Column('cut_off', sa.Integer(), nullable=True))
    op.add_column('cfg_trace_key', sa.Column('delta_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cfg_trace_key', 'delta_time')
    op.drop_column('cfg_trace_key', 'cut_off')
    # ### end Alembic commands ###
