"""Add default values function column

Revision ID: 6b4633b411e8
Revises: cfba6efd71fb
Create Date: 2024-05-07 09:23:36.659958

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.orm import Session

from ap.setting_module.models import MFunction

# revision identifiers, used by Alembic.
revision = '6b4633b411e8'
down_revision = 'cfba6efd71fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('m_function', sa.Column('coe_a_n_s', sa.Text(), nullable=True))
    op.add_column('m_function', sa.Column('coe_b_k_t', sa.Text(), nullable=True))
    op.add_column('m_function', sa.Column('coe_c', sa.Text(), nullable=True))

    conn = op.get_bind()
    m_function_count = conn.execute(sa.text('select count(*) from m_function')).fetchone()[0]
    # only migrate when `m_function` has existing data
    if m_function_count == 0:
        return
    session = Session(bind=conn)
    # delete all existing records
    session.query(MFunction).delete()
    session.commit()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('m_function', 'coe_c')
    op.drop_column('m_function', 'coe_b_k_t')
    op.drop_column('m_function', 'coe_a_n_s')
    # ### end Alembic commands ###
