"""Remove value_int and value_text in semi master, use value only

Revision ID: 7385ad240a01
Revises: 760205b453af
Create Date: 2024-03-15 11:19:38.032389

"""
import sqlalchemy as sa
from alembic import op

from ap.setting_module.models import SemiMaster

# revision identifiers, used by Alembic.
revision = '7385ad240a01'
down_revision = '760205b453af'
branch_labels = None
depends_on = None

combined_semi_master = sa.Table(
    SemiMaster.__tablename__,
    sa.MetaData(),
    sa.Column('factor', sa.SmallInteger()),
    sa.Column('value', sa.Text()),
    sa.Column('value_text', sa.Text()),
    sa.Column('value_int', sa.Integer()),
    sa.Column('group_id', sa.Integer()),
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('semi_master', sa.Column('value', sa.Text(), nullable=True))

    op.execute(
        sa.update(combined_semi_master).values(
            value=sa.func.coalesce(
                sa.cast(combined_semi_master.c.value_int, sa.Text()),
                combined_semi_master.c.value_text,
            ),
        ),
    )

    op.drop_column('semi_master', 'value_text')
    op.drop_column('semi_master', 'value_int')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('semi_master', sa.Column('value_int', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('semi_master', sa.Column('value_text', sa.TEXT(), autoincrement=False, nullable=True))

    op.execute(sa.update(combined_semi_master).values(value_text=combined_semi_master.c.value))

    op.drop_column('semi_master', 'value')

    # ### end Alembic commands ###
