"""feat: create new column skip_merge

Revision ID: 75d839eac3e0
Revises: fd863d0b8735
Create Date: 2024-07-19 15:41:26.516915

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '75d839eac3e0'
down_revision = 'fd863d0b8735'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cfg_data_table', sa.Column('skip_merge', sa.Boolean(), nullable=True, server_default='false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cfg_data_table', 'skip_merge')
    # ### end Alembic commands ###
