"""Add column merge_flag to t_process

Revision ID: 782a39997ead
Revises: b1584422eb18
Create Date: 2024-03-12 11:45:20.086634

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '782a39997ead'
down_revision = 'b1584422eb18'
branch_labels = None
depends_on = None


def collect_transaction_tables(operation):
    conn = operation.get_bind()
    collect_transaction_table_name_sql = '''
SELECT c.relname FROM pg_class AS c
WHERE NOT EXISTS (SELECT 1 FROM pg_inherits AS i WHERE i.inhrelid = c.oid)
AND c.relkind IN ('r', 'p')
AND regexp_like(c.relName, 't_process_', 'i');'''
    cur = conn.execute(collect_transaction_table_name_sql)
    t_process_tables = []
    rows = cur.fetchall()
    for row in rows:
        t_process_tables.append(row[0])

    return t_process_tables


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    t_process_tables = collect_transaction_tables(op)
    for t_process_table in t_process_tables:
        op.add_column(t_process_table, sa.Column('merge_flag', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    t_process_tables = collect_transaction_tables(op)
    for t_process_table in t_process_tables:
        op.drop_column(t_process_table, 'merge_flag')
    # ### end Alembic commands ###
