"""Migrate raw_data_type bigint

Revision ID: 793efe016cdf
Revises: 1fe10e5a9e8e
Create Date: 2024-10-16 13:47:37.381038

"""
from alembic import op

from ap.common.constants import DataType, RawDataTypeDB
from ap.setting_module.models import CfgProcessColumn

# revision identifiers, used by Alembic.
revision = '793efe016cdf'
down_revision = '1fe10e5a9e8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sql = f'''
        UPDATE {CfgProcessColumn.__tablename__} SET data_type = '{DataType.TEXT.value}'
        WHERE {CfgProcessColumn.raw_data_type.name}
        in ('{RawDataTypeDB.BOOLEAN.value}', '{RawDataTypeDB.CATEGORY.value}', '{RawDataTypeDB.BIG_INT.value}');
        '''
    op.execute(sql)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    ...
    # ### end Alembic commands ###
