"""add new cfg_request and cfg_option table

Revision ID: 7b4274b851ac
Revises: c653f7ef003d
Create Date: 2023-12-21 15:09:43.737589

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7b4274b851ac'
down_revision = 'c653f7ef003d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'cfg_request',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('params', sa.Text(), nullable=True),
        sa.Column('odf', sa.Text(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'cfg_option',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('option', sa.Text(), nullable=True),
        sa.Column('req_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(['req_id'], ['cfg_request.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cfg_option')
    op.drop_table('cfg_request')
    # ### end Alembic commands ###
