"""Remove index in t_csv_import

Revision ID: 91a8d55fbd39
Revises: 341a680e29bb
Create Date: 2024-06-17 09:29:35.208344

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '91a8d55fbd39'
down_revision = '341a680e29bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_t_csv_import_process_id_status_file_name', table_name='t_csv_import')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        'ix_t_csv_import_process_id_status_file_name',
        't_csv_import',
        ['process_id', 'status', 'file_name'],
        unique=False,
    )
    # ### end Alembic commands ###
