"""feat: add column `count_file`

Revision ID: a965241f0b5b
Revises: 75d839eac3e0
Create Date: 2024-07-23 09:08:54.450867

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a965241f0b5b'
down_revision = '75d839eac3e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_proc_data_count', sa.Column('count_file', sa.Integer(), nullable=True, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_proc_data_count', 'count_file')
    # ### end Alembic commands ###
