"""Add column detail_master_type into cfg_data_table

Revision ID: b1584422eb18
Revises: 7b4274b851ac
Create Date: 2024-03-08 10:12:57.671353

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b1584422eb18'
down_revision = 'dbbda08c8ca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cfg_csv_column', sa.Column('directory_no', sa.Integer(), nullable=True))
    op.add_column('cfg_data_source_csv', sa.Column('second_directory', sa.Text(), nullable=True))
    op.add_column('cfg_data_table', sa.Column('detail_master_type', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cfg_data_table', 'detail_master_type')
    op.drop_column('cfg_data_source_csv', 'second_directory')
    op.drop_column('cfg_csv_column', 'directory_no')
    # ### end Alembic commands ###
