"""Change m_config_equation structure

Revision ID: bdc47a76c084
Revises: 67118b8938cc
Create Date: 2024-04-15 10:48:45.948763

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bdc47a76c084'
down_revision = 'd026d5370dc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('m_config_equation', sa.Column('coe_a_n_s', sa.Text(), nullable=True))
    op.add_column('m_config_equation', sa.Column('coe_b_k_t', sa.Text(), nullable=True))
    op.alter_column(
        'm_config_equation',
        'coe_c',
        type_=sa.Text(),
        existing_type=postgresql.DOUBLE_PRECISION(),
    )

    op.execute(
        'UPDATE m_config_equation SET coe_a_n_s = coalesce(coe_a, par_n);',
    )
    op.execute(
        'UPDATE m_config_equation SET coe_b_k_t = coalesce(coe_b, par_k);',
    )

    op.drop_column('m_config_equation', 'coe_a')
    op.drop_column('m_config_equation', 'par_n')

    op.drop_column('m_config_equation', 'coe_b')
    op.drop_column('m_config_equation', 'par_k')

    op.drop_column('m_config_equation', 'par_j')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('m_config_equation', sa.Column('par_n', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column(
        'm_config_equation',
        sa.Column('coe_b', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    )
    op.add_column('m_config_equation', sa.Column('par_k', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('m_config_equation', sa.Column('par_j', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column(
        'm_config_equation',
        sa.Column('coe_a', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    )

    op.execute(
        'ALTER TABLE m_config_equation ALTER COLUMN coe_c TYPE double precision USING coe_c::double precision;',
    )

    op.execute(
        'UPDATE m_config_equation SET coe_a = coe_a_n_s::double precision;',
    )
    op.execute(
        'UPDATE m_config_equation SET par_n = coe_a_n_s::integer;',
    )
    op.execute(
        'UPDATE m_config_equation SET coe_b = coe_b_k_t::double precision;',
    )
    op.execute(
        'UPDATE m_config_equation SET par_k = coe_b_k_t::integer;',
    )
    op.drop_column('m_config_equation', 'coe_a_n_s')
    op.drop_column('m_config_equation', 'coe_b_k_t')

    # ### end Alembic commands ###
