"""Remote column show_name in cfg_process

Revision ID: c26254955074
Revises: 2d388310197b
Create Date: 2023-09-18 11:12:13.689342

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c26254955074'
down_revision = '2d388310197b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cfg_process', 'show_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cfg_process', sa.Column('show_name', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
