"""rename `eq_type_id` to `function_id`

Revision ID: c43f97b7dc2e
Revises: bdc47a76c084
Create Date: 2024-04-15 15:12:20.056379

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c43f97b7dc2e'
down_revision = 'bdc47a76c084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('m_config_equation', 'eq_type_id', nullable=False, new_column_name='function_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('m_config_equation', 'function_id', nullable=False, new_column_name='eq_type_id')
    # ### end Alembic commands ###
