"""Add column is_show_file_name

Revision ID: c491aa6bbe8d
Revises: 609db7dc5915
Create Date: 2024-04-23 10:08:56.292684

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c491aa6bbe8d'
down_revision = '609db7dc5915'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cfg_process', sa.Column('is_show_file_name', sa.Boolean(), nullable=True))
    op.alter_column('cfg_process_column', 'column_raw_name', existing_type=sa.TEXT(), nullable=True)
    sample_process_ids = ['2', '3', '4', '5', '6', '7']
    op.execute(
        f'UPDATE cfg_process SET is_show_file_name = false where id IN ({",".join(sample_process_ids)});',
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cfg_process_column', 'column_raw_name', existing_type=sa.TEXT(), nullable=False)
    op.drop_column('cfg_process', 'is_show_file_name')
    # ### end Alembic commands ###
