"""Add show_serial column

Revision ID: cfba6efd71fb
Revises: 2f4f6c3e7177
Create Date: 2024-05-06 17:27:01.307825

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.orm import Session

from ap.setting_module.models import MFunction

# revision identifiers, used by Alembic.
revision = 'cfba6efd71fb'
down_revision = '9c8bbf2d1914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('m_function', sa.Column('show_serial', sa.Boolean(), nullable=True))
    conn = op.get_bind()
    m_function_count = conn.execute(sa.text('select count(*) from m_function')).fetchone()[0]
    # only migrate when `m_function` has existing data
    if m_function_count == 0:
        return
    session = Session(bind=conn)
    # delete all existing records
    session.query(MFunction).delete()
    session.commit()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('m_function', 'show_serial')
    # ### end Alembic commands ###
