"""Change `cut_off` to float

Revision ID: db425f801f76
Revises: 69f8eb387b87
Create Date: 2024-07-03 17:18:03.394300

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'db425f801f76'
down_revision = '69f8eb387b87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cfg_trace_key', 'cut_off', existing_type=sa.Integer(), type_=sa.Float(), existing_nullable=False)
    op.alter_column(
        'cfg_trace_key',
        'delta_time',
        existing_type=sa.Integer(),
        type_=sa.Float(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cfg_trace_key', 'cut_off', existing_type=sa.Float(), type_=sa.Integer(), existing_nullable=False)
    op.alter_column(
        'cfg_trace_key',
        'delta_time',
        existing_type=sa.Float(),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
