"""Add auto link table

Revision ID: dbbda08c8ca4
Revises: 584add40584b
Create Date: 2024-03-07 17:35:27.038829

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'dbbda08c8ca4'
down_revision = '584add40584b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        't_auto_link',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('process_id', sa.Integer(), nullable=True),
        sa.Column('serial', sa.Text(), nullable=True),
        sa.Column('date_time', sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_t_auto_link_process_id'), 't_auto_link', ['process_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_auto_link_process_id'), table_name='t_auto_link')
    op.drop_table('t_auto_link')
    # ### end Alembic commands ###
