"""Add column unit into cfg_process_column tables

Revision ID: dd21fc341451
Revises: 75d839eac3e0
Create Date: 2024-07-31 16:13:32.826186

"""
import pandas as pd
import sqlalchemy as sa
from alembic import op
from sqlalchemy.orm import Session

from ap.setting_module.models import CfgProcessColumn, MData, MUnit

# revision identifiers, used by Alembic.
revision = 'dd21fc341451'
down_revision = 'a965241f0b5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cfg_process_column', sa.Column('unit', sa.Text(), nullable=True))

    session = Session(bind=op.get_bind())
    results = (
        session.query(MData.id, MUnit.unit).filter(MData.unit_id != 1).join(MUnit, MUnit.id == MData.unit_id).all()
    )
    df = pd.DataFrame(results, columns=[MData.id.name, MUnit.unit.name])
    dict_data_id_with_unit = df.set_index(MData.id.name)[MUnit.unit.name].to_dict()
    for data_id, unit in dict_data_id_with_unit.items():
        op.execute(
            f'''
            UPDATE {CfgProcessColumn.__tablename__} SET unit = '{unit}'
            WHERE {CfgProcessColumn.id.name} = {data_id};
            ''',
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cfg_process_column', 'unit')
    # ### end Alembic commands ###
