"""Change nullable of function_id

Revision ID: f5a6d1cb4741
Revises: c43f97b7dc2e
Create Date: 2024-04-15 15:44:25.296384

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f5a6d1cb4741'
down_revision = 'c43f97b7dc2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('m_config_equation', 'function_id', existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('m_config_equation', 'function_id', existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
