# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_src/models/common.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1cgrpc_src/models/common.proto\x12\rmodels.common"9\n\x14GenericRequestParams\x12\x0e\n\x06method\x18\x01 \x01(\t\x12\x11\n\tbinParams\x18\x02 \x01(\x0c"&\n\x0fGenericResponse\x12\x13\n\x0b\x62inResponse\x18\x01 \x01(\x0c\x62\x06proto3'
)


_GENERICREQUESTPARAMS = DESCRIPTOR.message_types_by_name['GenericRequestParams']
_GENERICRESPONSE = DESCRIPTOR.message_types_by_name['GenericResponse']
GenericRequestParams = _reflection.GeneratedProtocolMessageType(
    'GenericRequestParams',
    (_message.Message,),
    {
        'DESCRIPTOR': _GENERICREQUESTPARAMS,
        '__module__': 'grpc_src.models.common_pb2'
        # @@protoc_insertion_point(class_scope:models.common.GenericRequestParams)
    },
)
_sym_db.RegisterMessage(GenericRequestParams)

GenericResponse = _reflection.GeneratedProtocolMessageType(
    'GenericResponse',
    (_message.Message,),
    {
        'DESCRIPTOR': _GENERICRESPONSE,
        '__module__': 'grpc_src.models.common_pb2'
        # @@protoc_insertion_point(class_scope:models.common.GenericResponse)
    },
)
_sym_db.RegisterMessage(GenericResponse)

if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _GENERICREQUESTPARAMS._serialized_start = 47
    _GENERICREQUESTPARAMS._serialized_end = 104
    _GENERICRESPONSE._serialized_start = 106
    _GENERICRESPONSE._serialized_end = 144
# @@protoc_insertion_point(module_scope)
