# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_src/models/connection.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from grpc_src.models import config_pb2 as grpc__src_dot_models_dot_config__pb2  # noqa: F401

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n grpc_src/models/connection.proto\x12\x11models.connection\x1a\x1cgrpc_src/models/config.proto"q\n\x11RequestConnection\x12\x33\n\nrepository\x18\x01 \x01(\x0b\x32\x1f.models.config.MsgCfgRepository\x12\'\n\x04\x65\x64ge\x18\x02 \x01(\x0b\x32\x19.models.config.MsgCfgEdge"/\n\x0bGrpcSession\x12\x0f\n\x07repo_id\x18\x01 \x01(\x03\x12\x0f\n\x07\x65\x64ge_id\x18\x02 \x01(\x03"\x9b\x01\n\x12ResponseConnection\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x33\n\nrepository\x18\x03 \x01(\x0b\x32\x1f.models.config.MsgCfgRepository\x12/\n\x07session\x18\x04 \x01(\x0b\x32\x1e.models.connection.GrpcSession"&\n\x16RequestCheckConnection\x12\x0c\n\x04name\x18\x01 \x01(\t":\n\x17ResponseCheckConnection\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\tb\x06proto3'
)


_REQUESTCONNECTION = DESCRIPTOR.message_types_by_name['RequestConnection']
_GRPCSESSION = DESCRIPTOR.message_types_by_name['GrpcSession']
_RESPONSECONNECTION = DESCRIPTOR.message_types_by_name['ResponseConnection']
_REQUESTCHECKCONNECTION = DESCRIPTOR.message_types_by_name['RequestCheckConnection']
_RESPONSECHECKCONNECTION = DESCRIPTOR.message_types_by_name['ResponseCheckConnection']
RequestConnection = _reflection.GeneratedProtocolMessageType(
    'RequestConnection',
    (_message.Message,),
    {
        'DESCRIPTOR': _REQUESTCONNECTION,
        '__module__': 'grpc_src.models.connection_pb2'
        # @@protoc_insertion_point(class_scope:models.connection.RequestConnection)
    },
)
_sym_db.RegisterMessage(RequestConnection)

GrpcSession = _reflection.GeneratedProtocolMessageType(
    'GrpcSession',
    (_message.Message,),
    {
        'DESCRIPTOR': _GRPCSESSION,
        '__module__': 'grpc_src.models.connection_pb2'
        # @@protoc_insertion_point(class_scope:models.connection.GrpcSession)
    },
)
_sym_db.RegisterMessage(GrpcSession)

ResponseConnection = _reflection.GeneratedProtocolMessageType(
    'ResponseConnection',
    (_message.Message,),
    {
        'DESCRIPTOR': _RESPONSECONNECTION,
        '__module__': 'grpc_src.models.connection_pb2'
        # @@protoc_insertion_point(class_scope:models.connection.ResponseConnection)
    },
)
_sym_db.RegisterMessage(ResponseConnection)

RequestCheckConnection = _reflection.GeneratedProtocolMessageType(
    'RequestCheckConnection',
    (_message.Message,),
    {
        'DESCRIPTOR': _REQUESTCHECKCONNECTION,
        '__module__': 'grpc_src.models.connection_pb2'
        # @@protoc_insertion_point(class_scope:models.connection.RequestCheckConnection)
    },
)
_sym_db.RegisterMessage(RequestCheckConnection)

ResponseCheckConnection = _reflection.GeneratedProtocolMessageType(
    'ResponseCheckConnection',
    (_message.Message,),
    {
        'DESCRIPTOR': _RESPONSECHECKCONNECTION,
        '__module__': 'grpc_src.models.connection_pb2'
        # @@protoc_insertion_point(class_scope:models.connection.ResponseCheckConnection)
    },
)
_sym_db.RegisterMessage(ResponseCheckConnection)

if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _REQUESTCONNECTION._serialized_start = 85
    _REQUESTCONNECTION._serialized_end = 198
    _GRPCSESSION._serialized_start = 200
    _GRPCSESSION._serialized_end = 247
    _RESPONSECONNECTION._serialized_start = 250
    _RESPONSECONNECTION._serialized_end = 405
    _REQUESTCHECKCONNECTION._serialized_start = 407
    _REQUESTCHECKCONNECTION._serialized_end = 445
    _RESPONSECHECKCONNECTION._serialized_start = 447
    _RESPONSECHECKCONNECTION._serialized_end = 505
# @@protoc_insertion_point(module_scope)
