# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_src/models/etl_mapping.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n!grpc_src/models/etl_mapping.proto\x12\x12models.etl_mapping"\x93\x01\n\x0cMsgEtlColumn\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08table_id\x18\x02 \x01(\x03\x12\x13\n\x0b\x63olumn_name\x18\x03 \x01(\x03\x12 \n\x18\x62ridge_station_column_id\x18\x04 \x01(\x03\x12\x1b\n\x13is_auto_incremental\x18\x05 \x01(\x08\x12\x11\n\tis_ignore\x18\x06 \x01(\x08"g\n\x17MsgEtlColumnTransaction\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x16\n\x0e\x64\x61ta_source_id\x18\x02 \x01(\x03\x12\x13\n\x0b\x63olumn_name\x18\x03 \x01(\t\x12\x13\n\x0bmaster_type\x18\x04 \x01(\x03"\x94\x01\n\x0bMsgEtlTable\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x12\n\ntable_name\x18\x02 \x01(\x03\x12\x17\n\x0f\x64\x61tasource_type\x18\x03 \x01(\x03\x12\x15\n\rdatasource_id\x18\x04 \x01(\x03\x12\x14\n\x0cinsert_order\x18\x05 \x01(\x03\x12\x1f\n\x17\x62ridge_station_table_id\x18\x06 \x01(\x03\x62\x06proto3'
)


_MSGETLCOLUMN = DESCRIPTOR.message_types_by_name['MsgEtlColumn']
_MSGETLCOLUMNTRANSACTION = DESCRIPTOR.message_types_by_name['MsgEtlColumnTransaction']
_MSGETLTABLE = DESCRIPTOR.message_types_by_name['MsgEtlTable']
MsgEtlColumn = _reflection.GeneratedProtocolMessageType(
    'MsgEtlColumn',
    (_message.Message,),
    {
        'DESCRIPTOR': _MSGETLCOLUMN,
        '__module__': 'grpc_src.models.etl_mapping_pb2'
        # @@protoc_insertion_point(class_scope:models.etl_mapping.MsgEtlColumn)
    },
)
_sym_db.RegisterMessage(MsgEtlColumn)

MsgEtlColumnTransaction = _reflection.GeneratedProtocolMessageType(
    'MsgEtlColumnTransaction',
    (_message.Message,),
    {
        'DESCRIPTOR': _MSGETLCOLUMNTRANSACTION,
        '__module__': 'grpc_src.models.etl_mapping_pb2'
        # @@protoc_insertion_point(class_scope:models.etl_mapping.MsgEtlColumnTransaction)
    },
)
_sym_db.RegisterMessage(MsgEtlColumnTransaction)

MsgEtlTable = _reflection.GeneratedProtocolMessageType(
    'MsgEtlTable',
    (_message.Message,),
    {
        'DESCRIPTOR': _MSGETLTABLE,
        '__module__': 'grpc_src.models.etl_mapping_pb2'
        # @@protoc_insertion_point(class_scope:models.etl_mapping.MsgEtlTable)
    },
)
_sym_db.RegisterMessage(MsgEtlTable)

if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _MSGETLCOLUMN._serialized_start = 58
    _MSGETLCOLUMN._serialized_end = 205
    _MSGETLCOLUMNTRANSACTION._serialized_start = 207
    _MSGETLCOLUMNTRANSACTION._serialized_end = 310
    _MSGETLTABLE._serialized_start = 313
    _MSGETLTABLE._serialized_end = 461
# @@protoc_insertion_point(module_scope)
