# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_src/models/setting.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1dgrpc_src/models/setting.proto\x12\x0emodels.setting"5\n\x17GetDataBaseTableRequest\x12\x1a\n\x12\x63\x66g_data_source_id\x18\x01 \x01(\x03"X\n\x18GetDataBaseTableResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07\x64s_type\x18\x02 \x01(\t\x12\x0e\n\x06tables\x18\x03 \x03(\t\x12\x0b\n\x03msg\x18\x63 \x01(\t"R\n\x15GetLastRecordsRequest\x12\x16\n\x0e\x64\x61ta_source_id\x18\x01 \x01(\x03\x12\x12\n\ntable_name\x18\x02 \x01(\t\x12\r\n\x05limit\x18\x03 \x01(\x05"a\n\x16GetLastRecordsResponse\x12\x0c\n\x04\x63ols\x18\x01 \x01(\x0c\x12\x0c\n\x04rows\x18\x02 \x01(\x0c\x12\x17\n\x0f\x63ols_duplicated\x18\x03 \x01(\x0c\x12\x12\n\nfail_limit\x18\x04 \x01(\x0c"\x91\x01\n\x1eRequestCheckDataBaseConnection\x12\x0f\n\x07\x64\x62_type\x18\x01 \x01(\t\x12\x0c\n\x04host\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\t\x12\x0e\n\x06\x64\x62name\x18\x04 \x01(\t\x12\x0e\n\x06schema\x18\x05 \x01(\t\x12\x10\n\x08username\x18\x06 \x01(\t\x12\x10\n\x08password\x18\x07 \x01(\t"G\n\x1fResponseCheckDataBaseConnection\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x14\n\x0cis_connected\x18\x02 \x01(\x08"(\n\x18RequestCheckDiskCapacity\x12\x0c\n\x04name\x18\x01 \x01(\t"\xbd\x01\n\x19ResponseCheckDiskCapacity\x12\x13\n\x0b\x64isk_status\x18\x01 \x01(\t\x12\x14\n\x0cused_percent\x18\x02 \x01(\x05\x12\x13\n\x0bserver_info\x18\x03 \x01(\t\x12\x13\n\x0bserver_type\x18\x04 \x01(\t\x12\x1d\n\x15warning_limit_percent\x18\x05 \x01(\x05\x12\x1b\n\x13\x65rror_limit_percent\x18\x06 \x01(\x05\x12\x0f\n\x07message\x18\x63 \x01(\tb\x06proto3'
)


_GETDATABASETABLEREQUEST = DESCRIPTOR.message_types_by_name['GetDataBaseTableRequest']
_GETDATABASETABLERESPONSE = DESCRIPTOR.message_types_by_name['GetDataBaseTableResponse']
_GETLASTRECORDSREQUEST = DESCRIPTOR.message_types_by_name['GetLastRecordsRequest']
_GETLASTRECORDSRESPONSE = DESCRIPTOR.message_types_by_name['GetLastRecordsResponse']
_REQUESTCHECKDATABASECONNECTION = DESCRIPTOR.message_types_by_name['RequestCheckDataBaseConnection']
_RESPONSECHECKDATABASECONNECTION = DESCRIPTOR.message_types_by_name['ResponseCheckDataBaseConnection']
_REQUESTCHECKDISKCAPACITY = DESCRIPTOR.message_types_by_name['RequestCheckDiskCapacity']
_RESPONSECHECKDISKCAPACITY = DESCRIPTOR.message_types_by_name['ResponseCheckDiskCapacity']
GetDataBaseTableRequest = _reflection.GeneratedProtocolMessageType(
    'GetDataBaseTableRequest',
    (_message.Message,),
    {
        'DESCRIPTOR': _GETDATABASETABLEREQUEST,
        '__module__': 'grpc_src.models.setting_pb2'
        # @@protoc_insertion_point(class_scope:models.setting.GetDataBaseTableRequest)
    },
)
_sym_db.RegisterMessage(GetDataBaseTableRequest)

GetDataBaseTableResponse = _reflection.GeneratedProtocolMessageType(
    'GetDataBaseTableResponse',
    (_message.Message,),
    {
        'DESCRIPTOR': _GETDATABASETABLERESPONSE,
        '__module__': 'grpc_src.models.setting_pb2'
        # @@protoc_insertion_point(class_scope:models.setting.GetDataBaseTableResponse)
    },
)
_sym_db.RegisterMessage(GetDataBaseTableResponse)

GetLastRecordsRequest = _reflection.GeneratedProtocolMessageType(
    'GetLastRecordsRequest',
    (_message.Message,),
    {
        'DESCRIPTOR': _GETLASTRECORDSREQUEST,
        '__module__': 'grpc_src.models.setting_pb2'
        # @@protoc_insertion_point(class_scope:models.setting.GetLastRecordsRequest)
    },
)
_sym_db.RegisterMessage(GetLastRecordsRequest)

GetLastRecordsResponse = _reflection.GeneratedProtocolMessageType(
    'GetLastRecordsResponse',
    (_message.Message,),
    {
        'DESCRIPTOR': _GETLASTRECORDSRESPONSE,
        '__module__': 'grpc_src.models.setting_pb2'
        # @@protoc_insertion_point(class_scope:models.setting.GetLastRecordsResponse)
    },
)
_sym_db.RegisterMessage(GetLastRecordsResponse)

RequestCheckDataBaseConnection = _reflection.GeneratedProtocolMessageType(
    'RequestCheckDataBaseConnection',
    (_message.Message,),
    {
        'DESCRIPTOR': _REQUESTCHECKDATABASECONNECTION,
        '__module__': 'grpc_src.models.setting_pb2'
        # @@protoc_insertion_point(class_scope:models.setting.RequestCheckDataBaseConnection)
    },
)
_sym_db.RegisterMessage(RequestCheckDataBaseConnection)

ResponseCheckDataBaseConnection = _reflection.GeneratedProtocolMessageType(
    'ResponseCheckDataBaseConnection',
    (_message.Message,),
    {
        'DESCRIPTOR': _RESPONSECHECKDATABASECONNECTION,
        '__module__': 'grpc_src.models.setting_pb2'
        # @@protoc_insertion_point(class_scope:models.setting.ResponseCheckDataBaseConnection)
    },
)
_sym_db.RegisterMessage(ResponseCheckDataBaseConnection)

RequestCheckDiskCapacity = _reflection.GeneratedProtocolMessageType(
    'RequestCheckDiskCapacity',
    (_message.Message,),
    {
        'DESCRIPTOR': _REQUESTCHECKDISKCAPACITY,
        '__module__': 'grpc_src.models.setting_pb2'
        # @@protoc_insertion_point(class_scope:models.setting.RequestCheckDiskCapacity)
    },
)
_sym_db.RegisterMessage(RequestCheckDiskCapacity)

ResponseCheckDiskCapacity = _reflection.GeneratedProtocolMessageType(
    'ResponseCheckDiskCapacity',
    (_message.Message,),
    {
        'DESCRIPTOR': _RESPONSECHECKDISKCAPACITY,
        '__module__': 'grpc_src.models.setting_pb2'
        # @@protoc_insertion_point(class_scope:models.setting.ResponseCheckDiskCapacity)
    },
)
_sym_db.RegisterMessage(ResponseCheckDiskCapacity)

if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _GETDATABASETABLEREQUEST._serialized_start = 49
    _GETDATABASETABLEREQUEST._serialized_end = 102
    _GETDATABASETABLERESPONSE._serialized_start = 104
    _GETDATABASETABLERESPONSE._serialized_end = 192
    _GETLASTRECORDSREQUEST._serialized_start = 194
    _GETLASTRECORDSREQUEST._serialized_end = 276
    _GETLASTRECORDSRESPONSE._serialized_start = 278
    _GETLASTRECORDSRESPONSE._serialized_end = 375
    _REQUESTCHECKDATABASECONNECTION._serialized_start = 378
    _REQUESTCHECKDATABASECONNECTION._serialized_end = 523
    _RESPONSECHECKDATABASECONNECTION._serialized_start = 525
    _RESPONSECHECKDATABASECONNECTION._serialized_end = 596
    _REQUESTCHECKDISKCAPACITY._serialized_start = 598
    _REQUESTCHECKDISKCAPACITY._serialized_end = 638
    _RESPONSECHECKDISKCAPACITY._serialized_start = 641
    _RESPONSECHECKDISKCAPACITY._serialized_end = 830
# @@protoc_insertion_point(module_scope)
