# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_src/models/sync_config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n!grpc_src/models/sync_config.proto\x12\x12models.sync_config\x1a\x1cgrpc_src/models/config.proto\x1a grpc_src/models/connection.proto"\xca\x01\n\x11RequestSyncConfig\x12\x0f\n\x07repo_id\x18\x01 \x01(\x03\x12/\n\x07session\x18\x63 \x01(\x0b\x32\x1e.models.connection.GrpcSession\x12%\n\x06insert\x18\x02 \x01(\x0b\x32\x15.models.config.Insert\x12%\n\x06\x64\x65lete\x18\x03 \x01(\x0b\x32\x15.models.config.Delete\x12%\n\x06update\x18\x04 \x01(\x0b\x32\x15.models.config.Update"5\n\x12ResponseSyncConfig\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t"o\n\x17RequestSyncBridgeToEdge\x12/\n\x07session\x18\x63 \x01(\x0b\x32\x1e.models.connection.GrpcSession\x12\x0f\n\x07repo_id\x18\x01 \x01(\x03\x12\x12\n\nsync_order\x18\x02 \x01(\x03"\x8c\x02\n\x18ResponseSyncBridgeToEdge\x12\x0f\n\x07repo_id\x18\x01 \x01(\x03\x12%\n\x06insert\x18\x02 \x01(\x0b\x32\x15.models.config.Insert\x12%\n\x06\x64\x65lete\x18\x03 \x01(\x0b\x32\x15.models.config.Delete\x12%\n\x06update\x18\x04 \x01(\x0b\x32\x15.models.config.Update\x12\x1f\n\x17last_request_history_id\x18\x05 \x01(\x03\x12\x17\n\x0fis_get_all_data\x18\x06 \x01(\x08\x12\x19\n\x11transaction_group\x18\x07 \x01(\x03\x12\x15\n\ris_end_stream\x18\x63 \x01(\x08\x62\x06proto3'
)


_REQUESTSYNCCONFIG = DESCRIPTOR.message_types_by_name['RequestSyncConfig']
_RESPONSESYNCCONFIG = DESCRIPTOR.message_types_by_name['ResponseSyncConfig']
_REQUESTSYNCBRIDGETOEDGE = DESCRIPTOR.message_types_by_name['RequestSyncBridgeToEdge']
_RESPONSESYNCBRIDGETOEDGE = DESCRIPTOR.message_types_by_name['ResponseSyncBridgeToEdge']
RequestSyncConfig = _reflection.GeneratedProtocolMessageType(
    'RequestSyncConfig',
    (_message.Message,),
    {
        'DESCRIPTOR': _REQUESTSYNCCONFIG,
        '__module__': 'grpc_src.models.sync_config_pb2'
        # @@protoc_insertion_point(class_scope:models.sync_config.RequestSyncConfig)
    },
)
_sym_db.RegisterMessage(RequestSyncConfig)

ResponseSyncConfig = _reflection.GeneratedProtocolMessageType(
    'ResponseSyncConfig',
    (_message.Message,),
    {
        'DESCRIPTOR': _RESPONSESYNCCONFIG,
        '__module__': 'grpc_src.models.sync_config_pb2'
        # @@protoc_insertion_point(class_scope:models.sync_config.ResponseSyncConfig)
    },
)
_sym_db.RegisterMessage(ResponseSyncConfig)

RequestSyncBridgeToEdge = _reflection.GeneratedProtocolMessageType(
    'RequestSyncBridgeToEdge',
    (_message.Message,),
    {
        'DESCRIPTOR': _REQUESTSYNCBRIDGETOEDGE,
        '__module__': 'grpc_src.models.sync_config_pb2'
        # @@protoc_insertion_point(class_scope:models.sync_config.RequestSyncBridgeToEdge)
    },
)
_sym_db.RegisterMessage(RequestSyncBridgeToEdge)

ResponseSyncBridgeToEdge = _reflection.GeneratedProtocolMessageType(
    'ResponseSyncBridgeToEdge',
    (_message.Message,),
    {
        'DESCRIPTOR': _RESPONSESYNCBRIDGETOEDGE,
        '__module__': 'grpc_src.models.sync_config_pb2'
        # @@protoc_insertion_point(class_scope:models.sync_config.ResponseSyncBridgeToEdge)
    },
)
_sym_db.RegisterMessage(ResponseSyncBridgeToEdge)

if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _REQUESTSYNCCONFIG._serialized_start = 122
    _REQUESTSYNCCONFIG._serialized_end = 324
    _RESPONSESYNCCONFIG._serialized_start = 326
    _RESPONSESYNCCONFIG._serialized_end = 379
    _REQUESTSYNCBRIDGETOEDGE._serialized_start = 381
    _REQUESTSYNCBRIDGETOEDGE._serialized_end = 492
    _RESPONSESYNCBRIDGETOEDGE._serialized_start = 495
    _RESPONSESYNCBRIDGETOEDGE._serialized_end = 763
# @@protoc_insertion_point(module_scope)
