# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_src/models/trace_graph.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n!grpc_src/models/trace_graph.proto\x12\x12models.trace_graph"%\n\x10RequestTraceData\x12\x11\n\tdic_param\x18\x01 \x01(\x0c"l\n\x11ResponseTraceData\x12\n\n\x02\x64\x66\x18\x01 \x01(\x0c\x12\x1c\n\x14\x61\x63tual_record_number\x18\x02 \x01(\x05\x12\x16\n\x0eis_res_limited\x18\x03 \x01(\x08\x12\x15\n\ris_end_stream\x18\x63 \x01(\x08\x62\x06proto3'
)


_REQUESTTRACEDATA = DESCRIPTOR.message_types_by_name['RequestTraceData']
_RESPONSETRACEDATA = DESCRIPTOR.message_types_by_name['ResponseTraceData']
RequestTraceData = _reflection.GeneratedProtocolMessageType(
    'RequestTraceData',
    (_message.Message,),
    {
        'DESCRIPTOR': _REQUESTTRACEDATA,
        '__module__': 'grpc_src.models.trace_graph_pb2'
        # @@protoc_insertion_point(class_scope:models.trace_graph.RequestTraceData)
    },
)
_sym_db.RegisterMessage(RequestTraceData)

ResponseTraceData = _reflection.GeneratedProtocolMessageType(
    'ResponseTraceData',
    (_message.Message,),
    {
        'DESCRIPTOR': _RESPONSETRACEDATA,
        '__module__': 'grpc_src.models.trace_graph_pb2'
        # @@protoc_insertion_point(class_scope:models.trace_graph.ResponseTraceData)
    },
)
_sym_db.RegisterMessage(ResponseTraceData)

if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _REQUESTTRACEDATA._serialized_start = 57
    _REQUESTTRACEDATA._serialized_end = 94
    _RESPONSETRACEDATA._serialized_start = 96
    _RESPONSETRACEDATA._serialized_end = 204
# @@protoc_insertion_point(module_scope)
